import itertools

inputs = {
	'Subject': ["Testsubject"],
	'Message': ["Testmessage"],
	"Send to": ["3", "4", "5", "3,4", "3,5", "4,5", "3,4,5"],
	"knockout_enable": [1],
	"knockout_date[day]": [1],
	"knockout_date[month]": ["July"],
	"knockout_date[year]": [2021],
	"Priority": [1, 2, 3, 4, 5],
	"Send immediately": [1]
}

outputs = {
	'message': lambda options: options['Message'],
	'subject': lambda options: options['Subject'],
	'roleids': lambda options: options['Send to'],
	'knockoutdate': lambda options: 1625068800 if options["knockout_enable"] else 0,
	'priority': lambda options: options['Priority'] - 1,
	'instant': lambda options: options['Send immediately']
}

SCENARIO_PRE = "  Scenario: Autogenerated Scenario for dataintegrity\n" \
			   "    Given I log in as \"admin\"\n" \
			   '    And I navigate to "Plugins > Admin tools > Admin messenger > Send message" in site administration \n' \
			   '    And I set the following fields to these values:\n'

FEATURE_PRE = "@tool @tool_messenger\n" \
			  "Feature: Autogenerated dataintegrity check\n" \
			  "\n"


def my_product(inp):
	return (dict(zip(inp.keys(), values)) for values in itertools.product(*inp.values()))


def build_scenario(options):
	scenario = SCENARIO_PRE
	for key in options.keys():
		scenario += "      | " + str(key) + " | " + str(options[key]) + " |\n"
	scenario += "    And I press \"Send message\"\n"
	scenario += "    Then there should be a persistent with the following data:\n"
	for key in outputs.keys():
		scenario += "      | " + str(key) + " | " + str(outputs[key](options)) + " |\n"
	scenario += "\n\n"
	return scenario


def build_scenarios():
	features = FEATURE_PRE
	for scenario in my_product(inputs):
		features += build_scenario(scenario)
	test = open("../dataintegrity.feature", 'w')
	test.write(features)
	test.close()


build_scenarios()

